# Module 10 
# Assignment 1- working with NumPy

In [1]:
import numpy as np 

## Q1-
### step 1-
           :create an array with elements 1-20 using arange() function in numpy. 
### step 2- 
           :to find sum of elements in array = use sum() function 
           :to find mean of elements in array= use mean() function 
           :to find median of elements in array= use median() function 
           :to findstandard deviation of elements in array = use std() function 
### step 3 -
           :to find the index of each element greater than 10 we use where() function in numpy this function helps in selection of elements and gives index of the elements as result.

In [2]:
arr= np.arange(1,21)

print("Sum of elements :",np.sum(arr),"\n")
print("Mean of elements:",np.mean(arr),"\n")
print("Median of elements:", np.median(arr),"\n")
print( "Standard deviation of elements:", np.std(arr),"\n" )

indices = np.where(arr>10)
print( "index of elements greater than 10: ",indices)




Sum of elements : 210 

Mean of elements: 10.5 

Median of elements: 10.5 

Standard deviation of elements: 5.766281297335398 

index of elements greater than 10:  (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


## Q2-
### Step 1 - 
             :create a array with elements between 1-16 using arange() function 
             :Shape it into 4x4 matrix using reshape() function
### Step 2- 
             :use print() function to print the array
             :use transpose() function in numpy to get the transpose of matrix
             :use sum() and axis to get row-wise and column-wise sum of elements.
                   - axis =1: for row-wise sum 
                   - axis =0: for column-wise sum

In [3]:
arr2= np.arange(1,17).reshape(4,4)

print("4x4 array :\n",arr2,"\n")
print("transpose of array:\n",np.transpose(arr2),"\n")
print("row-wise sum of array:",np.sum(arr2,axis=1),"\n")
print("column-wise sum of array:",np.sum(arr2,axis=0))

4x4 array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

transpose of array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]] 

row-wise sum of array: [10 26 42 58] 

column-wise sum of array: [28 32 36 40]


## Q3- 
### Step 1-
           :random.randint() function in numpy is used to fill random integers as elements in array.
           it also helps in shaping the array into 2D.
### Step 2-
           :to get element- wise addition,subtraction and multiplication we use (+,-,*) operators respectively.
### Step 3-
           :to find dot product of 2 array we use dot() function from numpy.
     

In [4]:
matrix1 = np.random.randint(1,21,(3,3))
matrix2 = np.random.randint(1,21,(3,3))

print("element-wise addition:\n", matrix1 + matrix2)
print("element-wise subtraction:\n",matrix1 - matrix2)
print("element-wise multiplication:\n",matrix1 * matrix2)
print("Dot product:\n",np.dot(matrix1,matrix2))


element-wise addition:
 [[20 24 23]
 [24 26  8]
 [ 6 28  7]]
element-wise subtraction:
 [[-12 -10   1]
 [  2   8  -4]
 [ -2  -8   1]]
element-wise multiplication:
 [[ 64 119 132]
 [143 153  12]
 [  8 180  12]]
Dot product:
 [[189 347 122]
 [403 410 251]
 [158 196  94]]


## Q4-
### Step 1-
           :create a 1D array with 12 elements using arange()function.
### Step2-
           :reshape it into 2D array of 3x4 by using reshape()function.
### Step3- 
           :Slice the first 2 rows [0:2] and the last 2 columns[2:] from the 2D array with the slicing syntax 
                    -array_name[row,column]


In [5]:
arr4= np.arange(12)
print("1D array:\n",arr4)
reshaped=arr4.reshape(3,4)
print("3x4 2D array:\n",reshaped)
print("Slicing first 2 rows and last 2 columns:\n",reshaped[0:2,2:])

1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 2D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Slicing first 2 rows and last 2 columns:
 [[2 3]
 [6 7]]
